<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Ride quotes generated by the pricing engine (often triggered by the AI layer).
 * A quote is a time-limited price estimate that can be converted into a booking.
 * Quotes expire to prevent stale pricing from being used.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ride_quotes', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('quote_code')->unique();

            // Nullable: anonymous users (e.g. chatbot pre-auth) can get quotes
            $table->foreignUuid('customer_id')->nullable()->constrained('users')->nullOnDelete();

            $table->string('pickup_address');
            $table->decimal('pickup_lat', 10, 7);
            $table->decimal('pickup_lng', 10, 7);
            $table->string('destination_address');
            $table->decimal('destination_lat', 10, 7);
            $table->decimal('destination_lng', 10, 7);

            $table->timestamp('pickup_time');
            $table->decimal('estimated_distance_km', 8, 2);
            $table->unsignedSmallInteger('estimated_duration_minutes');
            $table->decimal('estimated_price', 10, 2);
            $table->string('currency', 3)->default('EUR');

            // Surge pricing multiplier — 1.00 = no surge
            $table->decimal('surge_multiplier', 5, 2)->default(1.00);

            $table->unsignedTinyInteger('passengers')->default(1);
            $table->string('vehicle_type'); // App\Enums\VehicleType

            // jsonb: available payment methods for this quote context
            $table->jsonb('payment_methods')->nullable();

            // false when the route/area is not covered by the service
            $table->boolean('serviceable')->default(true);

            $table->timestamp('expires_at');
            $table->timestamps();

            $table->index('customer_id');
            $table->index('expires_at');
            $table->index('quote_code');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ride_quotes');
    }
};
